# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import c2p.framework.models.models_pb2 as models__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\x11\x63\x32p.framework.api\x1a\x0cmodels.proto\"\x12\n\x10GetSchemaRequest\"(\n\x11GetSchemaResponse\x12\x13\n\x0bjson_schema\x18\x01 \x01(\x0c\"\"\n\x10\x43onfigureRequest\x12\x0e\n\x06\x63onfig\x18\x01 \x01(\x0c\"\"\n\x11\x43onfigureResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\t\"B\n\x12RemediationRequest\x12,\n\x08\x66indings\x18\x01 \x03(\x0b\x32\x1a.c2p.framework.api.Finding\"$\n\x13RemediationResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\t\"<\n\x0fGenerateRequest\x12)\n\x06policy\x18\x01 \x01(\x0b\x32\x19.c2p.framework.api.Policy\"!\n\x10GenerateResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\t\"\r\n\x0bScanRequest\"K\n\x0cScanResponse\x12,\n\x06result\x18\x01 \x01(\x0b\x32\x1c.c2p.framework.api.PVPResult\x12\r\n\x05\x65rror\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSCHEMAREQUEST']._serialized_start=51
  _globals['_GETSCHEMAREQUEST']._serialized_end=69
  _globals['_GETSCHEMARESPONSE']._serialized_start=71
  _globals['_GETSCHEMARESPONSE']._serialized_end=111
  _globals['_CONFIGUREREQUEST']._serialized_start=113
  _globals['_CONFIGUREREQUEST']._serialized_end=147
  _globals['_CONFIGURERESPONSE']._serialized_start=149
  _globals['_CONFIGURERESPONSE']._serialized_end=183
  _globals['_REMEDIATIONREQUEST']._serialized_start=185
  _globals['_REMEDIATIONREQUEST']._serialized_end=251
  _globals['_REMEDIATIONRESPONSE']._serialized_start=253
  _globals['_REMEDIATIONRESPONSE']._serialized_end=289
  _globals['_GENERATEREQUEST']._serialized_start=291
  _globals['_GENERATEREQUEST']._serialized_end=351
  _globals['_GENERATERESPONSE']._serialized_start=353
  _globals['_GENERATERESPONSE']._serialized_end=386
  _globals['_SCANREQUEST']._serialized_start=388
  _globals['_SCANREQUEST']._serialized_end=401
  _globals['_SCANRESPONSE']._serialized_start=403
  _globals['_SCANRESPONSE']._serialized_end=478
# @@protoc_insertion_point(module_scope)
