# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import c2p.framework.models.messages_pb2 as messages__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in scanner_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScanningProviderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSchema = channel.unary_unary(
                '/c2p.framework.api.ScanningProvider/GetSchema',
                request_serializer=messages__pb2.GetSchemaRequest.SerializeToString,
                response_deserializer=messages__pb2.GetSchemaResponse.FromString,
                _registered_method=True)
        self.UpdateConfiguration = channel.unary_unary(
                '/c2p.framework.api.ScanningProvider/UpdateConfiguration',
                request_serializer=messages__pb2.ConfigureRequest.SerializeToString,
                response_deserializer=messages__pb2.ConfigureResponse.FromString,
                _registered_method=True)
        self.Generate = channel.unary_unary(
                '/c2p.framework.api.ScanningProvider/Generate',
                request_serializer=messages__pb2.GenerateRequest.SerializeToString,
                response_deserializer=messages__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.Scan = channel.unary_unary(
                '/c2p.framework.api.ScanningProvider/Scan',
                request_serializer=messages__pb2.ScanRequest.SerializeToString,
                response_deserializer=messages__pb2.ScanResponse.FromString,
                _registered_method=True)


class ScanningProviderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSchema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateConfiguration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Generate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Scan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScanningProviderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchema,
                    request_deserializer=messages__pb2.GetSchemaRequest.FromString,
                    response_serializer=messages__pb2.GetSchemaResponse.SerializeToString,
            ),
            'UpdateConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConfiguration,
                    request_deserializer=messages__pb2.ConfigureRequest.FromString,
                    response_serializer=messages__pb2.ConfigureResponse.SerializeToString,
            ),
            'Generate': grpc.unary_unary_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=messages__pb2.GenerateRequest.FromString,
                    response_serializer=messages__pb2.GenerateResponse.SerializeToString,
            ),
            'Scan': grpc.unary_unary_rpc_method_handler(
                    servicer.Scan,
                    request_deserializer=messages__pb2.ScanRequest.FromString,
                    response_serializer=messages__pb2.ScanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'c2p.framework.api.ScanningProvider', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('c2p.framework.api.ScanningProvider', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScanningProvider(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/c2p.framework.api.ScanningProvider/GetSchema',
            messages__pb2.GetSchemaRequest.SerializeToString,
            messages__pb2.GetSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/c2p.framework.api.ScanningProvider/UpdateConfiguration',
            messages__pb2.ConfigureRequest.SerializeToString,
            messages__pb2.ConfigureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/c2p.framework.api.ScanningProvider/Generate',
            messages__pb2.GenerateRequest.SerializeToString,
            messages__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Scan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/c2p.framework.api.ScanningProvider/Scan',
            messages__pb2.ScanRequest.SerializeToString,
            messages__pb2.ScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
