# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scanner.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'scanner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import c2p.framework.models.messages_pb2 as messages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rscanner.proto\x12\x11\x63\x32p.framework.api\x1a\x0emessages.proto2\xea\x02\n\x10ScanningProvider\x12V\n\tGetSchema\x12#.c2p.framework.api.GetSchemaRequest\x1a$.c2p.framework.api.GetSchemaResponse\x12`\n\x13UpdateConfiguration\x12#.c2p.framework.api.ConfigureRequest\x1a$.c2p.framework.api.ConfigureResponse\x12S\n\x08Generate\x12\".c2p.framework.api.GenerateRequest\x1a#.c2p.framework.api.GenerateResponse\x12G\n\x04Scan\x12\x1e.c2p.framework.api.ScanRequest\x1a\x1f.c2p.framework.api.ScanResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scanner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCANNINGPROVIDER']._serialized_start=53
  _globals['_SCANNINGPROVIDER']._serialized_end=415
# @@protoc_insertion_point(module_scope)
